config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'homes#index'
  resources :photos
  resources :albums
  
  namespace :api do
    namespace :v1 do
      
      resources :photos
      resources :albums

      devise_scope :user do
        get "/users" , to: "users#index"
        post "/users/sign_up", to: "registrations#create"
        post "/users/sign_in", to: "sessions#create"
        delete "/logout", to: "sessions#destroy"
        post "/confirm_email", to: "confirmations#confirm_email"
      end

      resources :quotes 

      # routing error path
      match '*path', to: 'base#routing_error', via: %i[get post put patch delete]
      root to: 'base#routing_error'

    end
  end
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy

  validates :name, presence: true,  :uniqueness => {:scope=>:user_id}
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.order('created_at')
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      flash[:notice] = "Successfully added new album!"
      redirect_to albums_path
    else
      flash[:alert] = "Error adding new album!"
      render :new
    end
  end

  def destroy
    @album = Album.find(params[:id])
    if @album.destroy
      flash[:notice] = "Successfully deleted album!"
      redirect_to albums_path
    else
      flash[:alert] = "Error deleting album!"
    end
  end

  def show
    @albums = current_user.albums
    @album = @albums.find(params[:id])
  end

  private
  
  def album_params
    params.require(:album).permit(:name, :user_id)
  end
  
end

app/controllers/api/v1/albums_controller.rb
class Api::V1::AlbumsController < Api::V1::AuthenticatedController

  # GET /api/v1/albums
  def index
    authorize_user!

    begin
      @albums = current_user.albums.order('created_at')

    rescue => e
      render_exception(e, 422) && return
    end
    render json: AlbumSerializer.new(@albums).serializable_hash
  end

  # POST /api/v1/albums
  def create
    authorize_user!
    
    begin
      album = Album.create!(album_params.merge(user_id: current_user.id))

    rescue => e
      render_exception(e, 422) && return
    end
    json_response(AlbumSerializer.new(album).serializable_hash[:data][:attributes]) 
  end

  # DELETE /api/v1/albums/:id
  def destroy
    authorize_user!

    begin
      @album = Album.find(params[:id])
      validate!(@album.user_id)
      @album.destroy

    rescue => e
      render_exception(e, 422) && return
    end
    render json: { success: true, data: {}, errors: [] }, status: 200
  end

  # GET /api/v1/albums/:id
  def show
    authorize_user!

    begin
      @album = Album.find(params[:id])
      validate!(@album.user_id)

    rescue => e
      render_exception(e, 422) && return
    end
    json_response(AlbumSerializer.new(@album).serializable_hash[:data][:attributes]) 
  end

  private
  def album_params
    params.require(:album).permit(:name)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/index.html.erb
<div class="mx-4 my-4">
  <div class="page-header border-secondary pl-2" style="border-left:4px solid; border-bottom:1px solid">
    <h1>All Albums</h1>
  </div>
  <div>
    <div class="row my-3">
      <% @albums.each do |album| %>
        <!-- condition for finding photo of current user -->
        <% if current_user.id == album.user_id %>
          <div class="col-md-2">
            <ul class="navbar-nav me-auto mb-2 mt-2 mb-lg-0">
              <!-- Rendering image -->
              <%if album.photos.any?%>
                <li class="nav-item">
                  <a href="<%= album_path(album) %>" class="media-object">
                    <img src="<%= album.photos.first.image.url%>" class="img-responsive" style="border-radius:20px">
                  </a>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to image_tag("Gallery.png", class: 'img-responsive'), album_path(album) %>
                </li>
              <% end %>
              <li class="nav-item text-center">
                <%= album.name %>
              </li>
              <!-- Button to delete image -->
              <li class="nav-item text-center">
                <%= link_to 'Delete', album_path(album), class: 'btn btn-light btn-sm', method: :delete, data: {confirm: 'Are you sure?'} %>
              </li>
            </ul>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-md-2 mt-2">
    <div class="row border border-secondary"  style="width:160px; height:160px; border-radius:20px;">
      <ul class="navbar-nav me-auto mb-2 mt-2 mb-lg-0">
        <li class="nav-item", style ="list-style: none; " >
          <%= link_to image_tag("add.png", class: 'img-responsive my-5 mx-5', style: 'height:50px; width:50px'), new_album_path%>
        </li>
        <li class="text-center mt-2">
          <h6>New Album</h6>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/albums/new.html.erb
<div class="my-5 mx-4">
  <%= form_for @album, html: { multipart: true } do |f| %>

    <!-- hidden field of curent user id -->
    <div class="form-group">
      <%= f.number_field :user_id, id: :album_user_id, class: 'form-control', value: current_user.id, type: :hidden %>
    </div>

    <div class="form-group" style="width:30%">
      <h5>Album name : </h5>
      <%= f.text_field :name, class: 'form-control'%>
      <%= render "users/shared/error_messages", resource: @album %>
    </div>
     
    
    <div class="input-group mb-3">
      <%= f.submit 'Create Album', class: 'input-group-text' %>
    </div>

 
  <% end %>
</div>

app/views/albums/show.html.erb
<div class="my-3 mx-3">
  <div class="page-header border-secondary pl-2" style="border-left:4px solid; border-bottom:1px solid">
    <h1><%= @album.name %></h1>
  </div>
  <div class="row my-1">
    <% @album.photos.each do |album_photo| %>
      <div class="col-md-2 px-1">
        <ul class="navbar-nav me-auto mb-2 mt-2 mb-lg-0">
          <!-- Rendering image -->
          <li class="nav-item">
            <img src = "<%= album_photo.image.url %>", class="img-responsive">
          </li>
          <li class="nav-item text-center">
            <%= link_to 'Remove', photo_path(album_photo), class: 'btn btn-light btn-sm', method: :delete, data: {confirm: 'Are you sure?'} %>
          </li>
        </ul>
      </div>
    <% end %>
    <li class="nav-item mx-3 my-3" style="list-style:none">
      <%= link_to 'Back', albums_path , class: 'navbar-link' %>
    </li>
  </div>
</div>